FROM docker.io/library/ubuntu:26.04

# hadolint ignore=DL3008,DL3009
RUN apt-get update && apt-get install --no-install-recommends -y \
    systemd libpam-systemd dbus sudo \
    bash fish zsh \
    python3 tmux

RUN echo 'ubuntu ALL=(ALL:ALL) NOPASSWD: ALL' >/etc/sudoers.d/ubuntu \
    && chmod 0440 /etc/sudoers.d/ubuntu

RUN mkdir -p /etc/systemd/system/console-getty.service.d \
    && echo '[Service]' >/etc/systemd/system/console-getty.service.d/override.conf \
    && echo 'SetCredential=agetty.autologin:ubuntu' >>/etc/systemd/system/console-getty.service.d/override.conf

ENTRYPOINT ["/usr/lib/systemd/systemd"]
