#!/usr/bin/env python3

import base64
import json
import os
import os.path
import shutil
import subprocess
import sys
from pathlib import Path

TMUX_PATH = shutil.which("tmux") or ""
SCRIPT_PATH = os.path.realpath(__file__)

STATE_FILE = (
    Path(os.environ.get("XDG_STATE_HOME") or Path.home() / ".local/state")
    / "tmux-rr.json"
)

SESSIONS_FORMAT = {
    "session_name": "#{session_name}",
    "session_windows": "#{session_windows}",
    "windows": [],
}

WINDOWS_FORMAT = {
    "window_index": "#{window_index}",
    "window_name": "#{window_name}",
    "window_layout": "#{window_layout}",
    "window_panes": "#{window_panes}",
    "window_width": "#{window_width}",
    "window_height": "#{window_height}",
    "panes": [],
}

PANES_FORMAT = {
    "pane_index": "#{pane_index}",
    "pane_current_path": "#{pane_current_path}",
    "pane_current_command": "#{pane_current_command}",
    "command": "#{@tmux-rr-command}",
}

HELP_MESSAGE = """
Usage: tmux-rr <COMMAND>

Commands:
  clear          Remove saved state file
  save           Dump all sessions to state file
  init <SHELL>   Print shell integration (bash, fish, zsh)
  restore        Restore sessions from state file
""".strip()

SYSTEMD_UNIT = f"""
[Unit]
Description=tmux-rr

[Service]
ExecStart={TMUX_PATH} -D
ExecStartPost=-{SCRIPT_PATH} restore
ExecStop=-{SCRIPT_PATH} save
ExecStop={TMUX_PATH} kill-server

[Install]
WantedBy=default.target
""".strip()

# TODO: impl
INIT_BASH = """
echo TODO
""".strip()

INIT_FISH = f"""
mkdir -p "$HOME/.config/systemd/user" "$HOME/.config/systemd/user/default.target.wants"
printf '%s' '{SYSTEMD_UNIT}' > "$HOME/.config/systemd/user/tmux-rr.service"
ln -fs "$HOME/.config/systemd/user/tmux-rr.service" "$HOME/.config/systemd/user/default.target.wants/tmux-rr.service"
function __tmux_rr_command_saver --on-event fish_preexec
    test -n "$TMUX" && tmux -N set-option -pq @tmux-rr-command "$(echo $argv | base64 -w0)"
end
function __tmux_rr_command_saver --on-event fish_postexec
    test -n "$TMUX" && tmux -N set-option -pqu @tmux-rr-command
end
""".strip()

# TODO: impl
INIT_ZSH = """
echo TODO
""".strip()


def clear():
    STATE_FILE.unlink(missing_ok=True)


def save():
    state = {
        "settings": {
            "automatic-rename": subprocess.check_output(
                [TMUX_PATH, "show-options", "-gqv", "automatic-rename"], text=True
            ).strip(),
        },
        "sessions": [
            json.loads(session)
            for session in subprocess.check_output(
                [TMUX_PATH, "list-sessions", "-F", json.dumps(SESSIONS_FORMAT)],
                text=True,
            ).splitlines()
        ],
    }
    for session_state in state["sessions"]:
        session_state["windows"] = [
            json.loads(window)
            for window in subprocess.check_output(
                [
                    TMUX_PATH,
                    "list-windows",
                    "-t",
                    f"={session_state['session_name']}",
                    "-F",
                    json.dumps(WINDOWS_FORMAT),
                ],
                text=True,
            ).splitlines()
        ]
        for window_state in session_state["windows"]:
            window_state["panes"] = [
                json.loads(pane)
                for pane in subprocess.check_output(
                    [
                        TMUX_PATH,
                        "list-panes",
                        "-t",
                        f"={session_state['session_name']}:{window_state['window_index']}",
                        "-F",
                        json.dumps(PANES_FORMAT),
                    ],
                    text=True,
                ).splitlines()
            ]
            for pane_state in window_state["panes"]:
                pane_state["scrollback"] = base64.b64encode(
                    subprocess.check_output(
                        [
                            TMUX_PATH,
                            "capture-pane",
                            "-t",
                            f"={session_state['session_name']}:{window_state['window_index']}.{pane_state['pane_index']}",
                            "-epJ",
                            "-S",
                            "0",
                        ]
                    )
                ).decode()
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.touch(mode=0o600, exist_ok=True)
    STATE_FILE.chmod(0o600)
    STATE_FILE.write_text(json.dumps(state, indent=2), encoding="utf-8")


def restore():
    state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    for session_state in state["sessions"]:
        for window_state in session_state["windows"]:
            for pane_state in window_state["panes"][:1]:
                if (
                    subprocess.call(
                        [
                            TMUX_PATH,
                            "has-session",
                            "-t",
                            f"={session_state['session_name']}",
                        ]
                    )
                    > 0
                ):
                    pane_state["pane_id"] = subprocess.check_output(
                        [
                            TMUX_PATH,
                            "new-session",
                            "-dPF",
                            "#{pane_id}",
                            "-x",
                            window_state["window_width"],
                            "-y",
                            window_state["window_height"],
                            "-s",
                            session_state["session_name"],
                            "-n",
                            window_state["window_name"],
                            "-c",
                            pane_state["pane_current_path"],
                            "sleep",
                            "infinity",
                        ],
                        text=True,
                    ).strip()
                else:
                    pane_state["pane_id"] = subprocess.check_output(
                        [
                            TMUX_PATH,
                            "new-window",
                            "-dPF",
                            "#{pane_id}",
                            "-t",
                            f"={session_state['session_name']}",
                            "-n",
                            window_state["window_name"],
                            "-c",
                            pane_state["pane_current_path"],
                            "sleep",
                            "infinity",
                        ],
                        text=True,
                    ).strip()
            for pane_state in window_state["panes"][1:]:
                pane_state["pane_id"] = subprocess.check_output(
                    [
                        TMUX_PATH,
                        "split-window",
                        "-dPF",
                        "#{pane_id}",
                        "-t",
                        f"={session_state['session_name']}:{{end}}",
                        "-c",
                        pane_state["pane_current_path"],
                        "sleep",
                        "infinity",
                    ],
                    text=True,
                ).strip()
                subprocess.check_call(
                    [
                        TMUX_PATH,
                        "resize-pane",
                        "-t",
                        pane_state["pane_id"],
                        "-U",
                        "999",
                    ]
                )
            subprocess.check_call(
                [
                    TMUX_PATH,
                    "select-layout",
                    "-t",
                    f"={session_state['session_name']}:{{end}}",
                    window_state["window_layout"],
                ]
            )
            for pane_state in window_state["panes"]:
                subprocess.check_call(
                    [
                        TMUX_PATH,
                        "respawn-pane",
                        "-k",
                        "-t",
                        pane_state["pane_id"],
                        "-c",
                        pane_state["pane_current_path"],
                        "sh",
                        "-c",
                        'tmux wait-for tmux-rr; exec "$SHELL" -li',
                    ]
                )
                Path(
                    subprocess.check_output(
                        [
                            TMUX_PATH,
                            "display-message",
                            "-pt",
                            pane_state["pane_id"],
                            "#{pane_tty}",
                        ],
                        text=True,
                    ).strip()
                ).write_bytes(base64.b64decode(pane_state["scrollback"], validate=True))
                subprocess.check_call([TMUX_PATH, "wait-for", "-S", "tmux-rr"])


def help():
    print(HELP_MESSAGE)
    exit(1)


def init_bash():
    print(INIT_BASH)


def init_fish():
    print(INIT_FISH)


def init_zsh():
    print(INIT_ZSH)


if __name__ == "__main__":
    if len(sys.argv) == 1 or sys.argv[1] == "help":
        help()
    elif sys.argv[1] == "clear":
        clear()
    elif sys.argv[1] == "save":
        save()
    elif sys.argv[1] == "init":
        if len(sys.argv) == 2:
            help()
        elif sys.argv[2] == "bash":
            init_bash()
        elif sys.argv[2] == "fish":
            init_fish()
        elif sys.argv[2] == "zsh":
            init_zsh()
        else:
            help()
    elif sys.argv[1] == "restore":
        restore()
