[settings]
lockfile = true

[tools]
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"pipx:robotcode" = { version = "latest", extras = "all" }
"pipx:robotframework-robocop" = "latest"
"pipx:robotframework" = "latest"
golangci-lint = "latest"
go = "latest"
uv = "latest"

[tasks.build]
run = "go build ./cmd/tmux-rr"

[tasks.image-build]
depends = ["build"]
run = "podman build -t tmux-rr ."

[tasks.e2e-tests]
depends = ["image-build"]
run = "robot --loglevel TRACE --outputdir e2e/results -- e2e/tests.robot"

[tasks.unit-tests]
run = "go test -v ./..."

[tasks.tests]
depends = ["unit-tests", "e2e-tests"]

[tasks.container]
depends = ["image-build"]
run = "podman run --cap-add SYS_ADMIN -it --rm -v .:/wd -w /wd tmux-rr"
