name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Install go
        uses: actions/setup-go@v7 # zizmor: ignore[unpinned-uses]

      - name: Instal rf
        run: pipx install robotframework

      - name: Run tests
        run: make ci

      - name: Publish results
        if: always()
        uses: actions/upload-artifact@v7 # zizmor: ignore[unpinned-uses]
        with:
          name: log.html
          path: e2e/results/log.html
          archive: false
